# Generated by Django 2.2.3 on 2019-08-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0003_auto_20190120_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='chinook.Artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='chinook.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='chinook.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_type', to='chinook.MediaType'),
        ),
    ]
